# Generated by Django 3.2.5 on 2022-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.TextField(),
        ),
    ]
