# Generated by Django 3.2.5 on 2022-12-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateur', '0002_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='EnNoun',
        ),
        migrations.RenameField(
            model_name='ennoun',
            old_name='file',
            new_name='en_noun',
        ),
    ]
